const express = require("express")
const Port = process.env.Port||5000
const  cors = require("cors")
const app = express()
const routing = require("./Rounting/Seller_Rounting/Account_Routing/Account")
app.use(cors())
app.use(express.urlencoded({extended:true}))
app.use(express.json())
app.use('/',routing)
app.listen(Port,()=>console.log("The server is running on port",Port))
